/**
 * Curated sample data for the Entra ID module's look-around window.
 * Shapes MUST match the real hooks exactly (`useEntraUsers`, `useGroups`,
 * `useEnterpriseApps`, `useConditionalAccess`) so swapping the data source
 * never changes render code. See `useModulePhase`.
 */

import type { EntraUser } from "@/src/types/entraUsers";
import type { GroupListItem } from "@/src/types/groups";
import type { EnterpriseAppListItem, EnterpriseAppStats } from "@/src/types/enterpriseApps";
import type { CaPolicyListItem, CaStats, CaTenantRecommendations } from "@/src/types/conditionalAccess";

export const sampleEntraUsers: EntraUser[] = [
  {
    id: "sample-user-1",
    displayName: "Amelia Rowe",
    userPrincipalName: "amelia.rowe@northwind-traders.com",
    mail: "amelia.rowe@northwind-traders.com",
    jobTitle: "Chief Operating Officer",
    department: "Executive",
    officeLocation: "Seattle HQ",
    mobilePhone: "+1 206 555 0142",
    accountEnabled: true,
    assignedLicenses: [{ skuId: "c42b9cae-ea4f-4ab7-9717-81576235ccac" }],
    createdDateTime: "2022-01-10T09:00:00Z",
  },
  {
    id: "sample-user-2",
    displayName: "Daniel Okafor",
    userPrincipalName: "daniel.okafor@northwind-traders.com",
    mail: "daniel.okafor@northwind-traders.com",
    jobTitle: "IT Administrator",
    department: "Information Technology",
    officeLocation: "Seattle HQ",
    mobilePhone: "+1 206 555 0187",
    accountEnabled: true,
    assignedLicenses: [{ skuId: "c42b9cae-ea4f-4ab7-9717-81576235ccac" }],
    createdDateTime: "2022-02-03T09:00:00Z",
  },
  {
    id: "sample-user-3",
    displayName: "Priya Nair",
    userPrincipalName: "priya.nair@northwind-traders.com",
    mail: "priya.nair@northwind-traders.com",
    jobTitle: "Finance Director",
    department: "Finance",
    officeLocation: "Austin Office",
    mobilePhone: "+1 512 555 0119",
    accountEnabled: true,
    assignedLicenses: [{ skuId: "6fd2c87f-b296-42f0-b197-1e91e994b900" }],
    createdDateTime: "2022-03-21T09:00:00Z",
  },
  {
    id: "sample-user-4",
    displayName: "Marcus Bell",
    userPrincipalName: "marcus.bell@northwind-traders.com",
    mail: "marcus.bell@northwind-traders.com",
    jobTitle: "Sales Manager",
    department: "Sales",
    officeLocation: "Austin Office",
    mobilePhone: "+1 512 555 0164",
    accountEnabled: true,
    assignedLicenses: [{ skuId: "6fd2c87f-b296-42f0-b197-1e91e994b900" }],
    createdDateTime: "2022-04-15T09:00:00Z",
  },
  {
    id: "sample-user-5",
    displayName: "Sofia Marchetti",
    userPrincipalName: "sofia.marchetti@northwind-traders.com",
    mail: "sofia.marchetti@northwind-traders.com",
    jobTitle: "HR Business Partner",
    department: "Human Resources",
    officeLocation: "Remote",
    mobilePhone: "+1 206 555 0173",
    accountEnabled: true,
    assignedLicenses: [{ skuId: "c42b9cae-ea4f-4ab7-9717-81576235ccac" }],
    createdDateTime: "2022-05-02T09:00:00Z",
  },
  {
    id: "sample-user-6",
    displayName: "Ethan Wallace",
    userPrincipalName: "ethan.wallace@northwind-traders.com",
    mail: "ethan.wallace@northwind-traders.com",
    jobTitle: "Software Engineer",
    department: "Engineering",
    officeLocation: "Remote",
    mobilePhone: "+1 206 555 0198",
    accountEnabled: true,
    assignedLicenses: [{ skuId: "6fd2c87f-b296-42f0-b197-1e91e994b900" }],
    createdDateTime: "2022-06-18T09:00:00Z",
  },
  {
    id: "sample-user-7",
    displayName: "Grace Kim",
    userPrincipalName: "grace.kim@northwind-traders.com",
    mail: "grace.kim@northwind-traders.com",
    jobTitle: "Marketing Coordinator",
    department: "Marketing",
    officeLocation: "Austin Office",
    mobilePhone: "+1 512 555 0132",
    accountEnabled: false,
    assignedLicenses: [],
    createdDateTime: "2022-07-09T09:00:00Z",
  },
  {
    id: "sample-user-8",
    displayName: "Liam Fitzgerald",
    userPrincipalName: "liam.fitzgerald@northwind-traders.com",
    mail: "liam.fitzgerald@northwind-traders.com",
    jobTitle: "Procurement Specialist",
    department: "Operations",
    officeLocation: "Seattle HQ",
    mobilePhone: "+1 206 555 0155",
    accountEnabled: false,
    assignedLicenses: [],
    createdDateTime: "2022-08-27T09:00:00Z",
  },
];

export const sampleGroups: GroupListItem[] = [
  {
    id: "sample-group-1",
    displayName: "Finance Team",
    description: "Finance department staff and budget approvers.",
    mail: "finance-team@northwind-traders.com",
    mailEnabled: true,
    mailNickname: "finance-team",
    securityEnabled: true,
    groupTypes: ["Unified"],
    createdDateTime: "2022-01-15T09:00:00Z",
  },
  {
    id: "sample-group-2",
    displayName: "IT Administrators",
    description: "Privileged access group for IT staff.",
    mail: undefined,
    mailEnabled: false,
    securityEnabled: true,
    groupTypes: [],
    createdDateTime: "2022-01-20T09:00:00Z",
  },
  {
    id: "sample-group-3",
    displayName: "All Employees",
    description: "Dynamic group containing every active employee.",
    mail: "all-employees@northwind-traders.com",
    mailEnabled: true,
    mailNickname: "all-employees",
    securityEnabled: true,
    groupTypes: ["Unified", "DynamicMembership"],
    createdDateTime: "2022-01-10T09:00:00Z",
    membershipRule: '(user.accountEnabled -eq true)',
    membershipRuleProcessingState: "On",
  },
  {
    id: "sample-group-4",
    displayName: "Sales Distribution List",
    description: "Distribution list for the regional sales team.",
    mail: "sales-dl@northwind-traders.com",
    mailEnabled: true,
    mailNickname: "sales-dl",
    securityEnabled: false,
    groupTypes: [],
    createdDateTime: "2022-02-11T09:00:00Z",
  },
  {
    id: "sample-group-5",
    displayName: "Engineering",
    description: "Product engineering team.",
    mail: "engineering@northwind-traders.com",
    mailEnabled: true,
    mailNickname: "engineering",
    securityEnabled: true,
    groupTypes: ["Unified"],
    createdDateTime: "2022-03-04T09:00:00Z",
  },
  {
    id: "sample-group-6",
    displayName: "Executive Leadership",
    description: "Company executives and officers.",
    mail: undefined,
    mailEnabled: false,
    securityEnabled: true,
    groupTypes: [],
    createdDateTime: "2022-01-05T09:00:00Z",
  },
];

export const sampleEnterpriseAppStats: EnterpriseAppStats = {
  total: 6,
  ssoConfigured: 4,
  needsAttention: 1,
  disabled: 1,
};

export const sampleEnterpriseApps: EnterpriseAppListItem[] = [
  {
    id: "sample-app-1",
    appId: "11111111-1111-4111-8111-111111111111",
    displayName: "Salesforce",
    publisher: "Salesforce.com, Inc.",
    logoUrl: null,
    ssoMode: "saml",
    accountEnabled: true,
    assignmentRequired: true,
    appType: "enterprise",
    createdDateTime: "2022-01-12T09:00:00Z",
    lastSignInDateTime: "2026-07-09T14:22:00Z",
    healthStatus: "healthy",
    chips: [{ key: "healthy", severity: "success" }],
  },
  {
    id: "sample-app-2",
    appId: "22222222-2222-4222-8222-222222222222",
    displayName: "Slack",
    publisher: "Slack Technologies, LLC",
    logoUrl: null,
    ssoMode: "oidc",
    accountEnabled: true,
    assignmentRequired: false,
    appType: "enterprise",
    createdDateTime: "2022-02-18T09:00:00Z",
    lastSignInDateTime: "2026-07-10T08:05:00Z",
    healthStatus: "healthy",
    chips: [{ key: "healthy", severity: "success" }],
  },
  {
    id: "sample-app-3",
    appId: "33333333-3333-4333-8333-333333333333",
    displayName: "DocuSign",
    publisher: "DocuSign, Inc.",
    logoUrl: null,
    ssoMode: "saml",
    accountEnabled: true,
    assignmentRequired: true,
    appType: "enterprise",
    createdDateTime: "2022-03-22T09:00:00Z",
    lastSignInDateTime: "2026-06-28T11:40:00Z",
    healthStatus: "warning",
    chips: [{ key: "cert_expiring", severity: "warning", days: 21 }],
  },
  {
    id: "sample-app-4",
    appId: "44444444-4444-4444-8444-444444444444",
    displayName: "Zoom",
    publisher: "Zoom Video Communications, Inc.",
    logoUrl: null,
    ssoMode: "saml",
    accountEnabled: true,
    assignmentRequired: false,
    appType: "enterprise",
    createdDateTime: "2022-04-02T09:00:00Z",
    lastSignInDateTime: "2026-07-08T16:12:00Z",
    healthStatus: "healthy",
    chips: [{ key: "healthy", severity: "success" }],
  },
  {
    id: "sample-app-5",
    appId: "55555555-5555-4555-8555-555555555555",
    displayName: "Expensify",
    publisher: "Expensify, Inc.",
    logoUrl: null,
    ssoMode: "none",
    accountEnabled: true,
    assignmentRequired: true,
    appType: "enterprise",
    createdDateTime: "2022-05-30T09:00:00Z",
    lastSignInDateTime: "2026-05-14T10:03:00Z",
    healthStatus: "warning",
    chips: [{ key: "broad_permissions", severity: "warning" }],
  },
  {
    id: "sample-app-6",
    appId: "66666666-6666-4666-8666-666666666666",
    displayName: "Legacy Timesheet Portal",
    publisher: "Northwind Internal",
    logoUrl: null,
    ssoMode: "none",
    accountEnabled: false,
    assignmentRequired: true,
    appType: "other",
    createdDateTime: "2021-11-01T09:00:00Z",
    lastSignInDateTime: "2025-09-02T09:00:00Z",
    healthStatus: "disabled",
    chips: [{ key: "disabled", severity: "muted" }],
  },
];

export const sampleCaStats: CaStats = {
  total: 5,
  enforced: 3,
  reportOnly: 1,
  coverageGaps: 1,
};

export const sampleCaRecommendations: CaTenantRecommendations = {
  recommendations: [
    {
      id: "sample-rec-1",
      severity: "warning",
      title: "Exclude break-glass accounts from all policies",
      description: "One or more emergency access accounts are not excluded from Conditional Access policies.",
      remediationSteps: ["Identify break-glass accounts", "Add them to the exclusion list on every policy"],
    },
  ],
  completionScore: 78,
  passedChecks: 7,
  totalChecks: 9,
};

export const sampleConditionalAccessPolicies: CaPolicyListItem[] = [
  {
    id: "sample-ca-1",
    displayName: "Require MFA for all users",
    state: "enabled",
    stateLabel: "On",
    assignedToSummary: "All users",
    assignedToCount: 248,
    excludedSummary: "Break-glass accounts",
    excludedCount: 2,
    targetAppsSummary: "All cloud apps",
    targetAppsCount: 0,
    controls: {
      mfa: true,
      compliantDevice: false,
      domainJoined: false,
      authStrength: null,
      block: false,
      signInFrequency: false,
      persistentBrowserSession: false,
    },
    includesAllUsers: true,
    legacyAuthTargeted: false,
    createdDateTime: "2022-01-16T09:00:00Z",
    modifiedDateTime: "2026-04-02T09:00:00Z",
    healthStatus: "healthy",
    chips: [{ key: "healthy", severity: "success" }],
  },
  {
    id: "sample-ca-2",
    displayName: "Block legacy authentication",
    state: "enabled",
    stateLabel: "On",
    assignedToSummary: "All users",
    assignedToCount: 248,
    excludedSummary: "None",
    excludedCount: 0,
    targetAppsSummary: "All cloud apps",
    targetAppsCount: 0,
    controls: {
      mfa: false,
      compliantDevice: false,
      domainJoined: false,
      authStrength: null,
      block: true,
      signInFrequency: false,
      persistentBrowserSession: false,
    },
    includesAllUsers: true,
    legacyAuthTargeted: true,
    createdDateTime: "2022-01-16T09:05:00Z",
    modifiedDateTime: "2022-01-16T09:05:00Z",
    healthStatus: "healthy",
    chips: [{ key: "healthy", severity: "success" }],
  },
  {
    id: "sample-ca-3",
    displayName: "Require compliant device for admins",
    state: "enabled",
    stateLabel: "On",
    assignedToSummary: "Directory role: Global Administrator",
    assignedToCount: 5,
    excludedSummary: "Break-glass accounts",
    excludedCount: 2,
    targetAppsSummary: "All cloud apps",
    targetAppsCount: 0,
    controls: {
      mfa: true,
      compliantDevice: true,
      domainJoined: false,
      authStrength: null,
      block: false,
      signInFrequency: false,
      persistentBrowserSession: false,
    },
    includesAllUsers: false,
    legacyAuthTargeted: false,
    createdDateTime: "2022-02-01T09:00:00Z",
    modifiedDateTime: "2026-01-11T09:00:00Z",
    healthStatus: "healthy",
    chips: [{ key: "healthy", severity: "success" }],
  },
  {
    id: "sample-ca-4",
    displayName: "Sign-in frequency for finance apps",
    state: "enabledForReportingButNotEnforced",
    stateLabel: "Report-only",
    assignedToSummary: "Group: Finance Team",
    assignedToCount: 14,
    excludedSummary: "None",
    excludedCount: 0,
    targetAppsSummary: "NetSuite, Concur",
    targetAppsCount: 2,
    controls: {
      mfa: false,
      compliantDevice: false,
      domainJoined: false,
      authStrength: null,
      block: false,
      signInFrequency: true,
      persistentBrowserSession: false,
    },
    includesAllUsers: false,
    legacyAuthTargeted: false,
    createdDateTime: "2026-03-05T09:00:00Z",
    modifiedDateTime: "2026-03-05T09:00:00Z",
    healthStatus: "warning",
    chips: [{ key: "report_only_too_long", severity: "warning", days: 128 }],
  },
  {
    id: "sample-ca-5",
    displayName: "Require MFA for guest access",
    state: "disabled",
    stateLabel: "Off",
    assignedToSummary: "Guests and external users",
    assignedToCount: 9,
    excludedSummary: "None",
    excludedCount: 0,
    targetAppsSummary: "All cloud apps",
    targetAppsCount: 0,
    controls: {
      mfa: true,
      compliantDevice: false,
      domainJoined: false,
      authStrength: null,
      block: false,
      signInFrequency: false,
      persistentBrowserSession: false,
    },
    includesAllUsers: false,
    legacyAuthTargeted: false,
    createdDateTime: "2022-06-10T09:00:00Z",
    modifiedDateTime: "2025-12-19T09:00:00Z",
    healthStatus: "danger",
    chips: [{ key: "disabled", severity: "muted" }],
  },
];
