/**
 * Curated sample data for the Purview module's look-around window.
 * Shown when `useModulePhase('purview').locked` is true — the shape MUST
 * match `useDlpAlerts()`'s real return type (`DlpAlert[]`, from
 * `src/types/purview.ts`) exactly, so swapping the data source never changes
 * render code. Only DLP alerts are sample data — Purview's data-map, catalog,
 * cost, and integrations data are NexusOne-owned infra and are never faked.
 */

import type { DlpAlert } from "@/src/types/purview";

export const SAMPLE_DLP_ALERTS: DlpAlert[] = [
  {
    id: "sample-dlp-001",
    displayName: "Credit card numbers shared via Exchange Online",
    severity: "high",
    status: "new",
    detectedAt: "2026-07-10T14:22:00.000Z",
    users: ["dana.ortiz@contoso.com"],
    location: "Exchange Online",
    portalUrl: null,
    detail: {
      policyName: "PCI-DSS — Payment Card Data",
      ruleName: "Credit card number detected in outbound mail",
      actions: ["Blocked email", "Notified sender"],
      whatHappened: "An email with 3 attachments containing unredacted credit card numbers was sent to an external recipient and blocked before delivery.",
      subject: "Q3 refund batch — customer statements",
      fileName: "refund-batch-q3.xlsx",
      recipients: ["billing@northwind-partners.com"],
      sensitiveInfoTypes: [
        { name: "Credit Card Number", count: 47, confidence: 95 },
        { name: "U.S. Social Security Number (SSN)", count: 3, confidence: 85 },
      ],
      eventCount: 1,
    },
  },
  {
    id: "sample-dlp-002",
    displayName: "Customer PII uploaded to unmanaged SharePoint site",
    severity: "high",
    status: "inProgress",
    detectedAt: "2026-07-09T09:05:00.000Z",
    users: ["marcus.lee@contoso.com"],
    location: "SharePoint Online",
    portalUrl: null,
    detail: {
      policyName: "U.S. PII — Data Protection Standard",
      ruleName: "Bulk PII upload to external-shared site",
      actions: ["Restricted access", "Notified admin"],
      whatHappened: "A spreadsheet containing customer names, addresses, and SSNs was uploaded to a site shared with an external domain.",
      subject: null,
      fileName: "customer-master-list-2026.xlsx",
      recipients: [],
      sensitiveInfoTypes: [
        { name: "U.S. Social Security Number (SSN)", count: 612, confidence: 92 },
        { name: "U.S. Physical Addresses", count: 598, confidence: 88 },
      ],
      eventCount: 1,
    },
  },
  {
    id: "sample-dlp-003",
    displayName: "Source code with embedded API keys shared externally",
    severity: "medium",
    status: "new",
    detectedAt: "2026-07-08T17:41:00.000Z",
    users: ["priya.natarajan@contoso.com"],
    location: "OneDrive for Business",
    portalUrl: null,
    detail: {
      policyName: "Credentials & Secrets Policy",
      ruleName: "API key pattern detected in shared file",
      actions: ["Notified sender"],
      whatHappened: "A configuration file containing a live Azure storage account key was shared via a public link.",
      subject: null,
      fileName: "app.config.sample.json",
      recipients: [],
      sensitiveInfoTypes: [
        { name: "Azure Storage Account Key", count: 1, confidence: 90 },
      ],
      eventCount: 1,
    },
  },
  {
    id: "sample-dlp-004",
    displayName: "Health record details discussed in Teams channel",
    severity: "medium",
    status: "inProgress",
    detectedAt: "2026-07-07T11:13:00.000Z",
    users: ["angela.ferreira@contoso.com", "tom.wicks@contoso.com"],
    location: "Microsoft Teams",
    portalUrl: null,
    detail: {
      policyName: "HIPAA — Protected Health Information",
      ruleName: "PHI keywords in chat message",
      actions: ["Notified admin"],
      whatHappened: "A Teams conversation referenced a patient's diagnosis and policy number in a channel with 40+ members.",
      subject: null,
      fileName: null,
      recipients: [],
      sensitiveInfoTypes: [
        { name: "Health Insurance Policy Number", count: 2, confidence: 78 },
      ],
      eventCount: 3,
    },
  },
  {
    id: "sample-dlp-005",
    displayName: "Repeated small transfers of financial data to personal email",
    severity: "high",
    status: "new",
    detectedAt: "2026-07-06T20:02:00.000Z",
    users: ["marcus.lee@contoso.com"],
    location: "Exchange Online",
    portalUrl: null,
    detail: {
      policyName: "PCI-DSS — Payment Card Data",
      ruleName: "Repeated low-volume exfiltration pattern",
      actions: ["Blocked email"],
      whatHappened: "The same user forwarded four separate emails containing bank account and routing numbers to a personal Gmail address over two days.",
      subject: "FW: vendor payout details",
      fileName: null,
      recipients: ["marcus.lee87@gmail.com"],
      sensitiveInfoTypes: [
        { name: "ABA Routing Number", count: 4, confidence: 91 },
        { name: "International Bank Account Number (IBAN)", count: 2, confidence: 89 },
      ],
      eventCount: 4,
    },
  },
  {
    id: "sample-dlp-006",
    displayName: "Passport scan stored in general-access Teams folder",
    severity: "low",
    status: "resolved",
    detectedAt: "2026-06-29T08:47:00.000Z",
    users: ["hannah.brooks@contoso.com"],
    location: "SharePoint Online",
    portalUrl: null,
    detail: {
      policyName: "U.S. PII — Data Protection Standard",
      ruleName: "Government ID document detected",
      actions: ["Moved to restricted folder"],
      whatHappened: "A scanned passport image was found in a Teams files folder accessible to the whole department; it was moved to a restricted-access location and the finding closed.",
      subject: null,
      fileName: "passport_scan_hbrooks.png",
      recipients: [],
      sensitiveInfoTypes: [
        { name: "U.S. Passport Number", count: 1, confidence: 96 },
      ],
      eventCount: 1,
    },
  },
  {
    id: "sample-dlp-007",
    displayName: "Marketing list export flagged for informational review",
    severity: "informational",
    status: "resolved",
    detectedAt: "2026-06-24T13:30:00.000Z",
    users: ["sofia.dimitrova@contoso.com"],
    location: "OneDrive for Business",
    portalUrl: null,
    detail: {
      policyName: "Data Handling — Informational",
      ruleName: "Bulk contact export flagged for review",
      actions: ["Logged for audit"],
      whatHappened: "A CSV export of newsletter subscriber emails was flagged for routine review; no policy violation was found.",
      subject: null,
      fileName: "newsletter-subscribers-june.csv",
      recipients: [],
      sensitiveInfoTypes: [
        { name: "Email Address", count: 2140, confidence: 60 },
      ],
      eventCount: 1,
    },
  },
  {
    id: "sample-dlp-008",
    displayName: "Contract with unredacted bank details sent to auditor",
    severity: "medium",
    status: "new",
    detectedAt: "2026-07-05T16:18:00.000Z",
    users: ["tom.wicks@contoso.com"],
    location: "Exchange Online",
    portalUrl: null,
    detail: {
      policyName: "PCI-DSS — Payment Card Data",
      ruleName: "Bank details detected in attachment",
      actions: ["Notified sender", "Notified admin"],
      whatHappened: "A signed vendor contract including unredacted bank account details was emailed to an external auditing firm's shared inbox.",
      subject: "Signed MSA — Q3 audit package",
      fileName: "vendor-msa-signed.pdf",
      recipients: ["audit-team@meridian-cpa.com"],
      sensitiveInfoTypes: [
        { name: "International Bank Account Number (IBAN)", count: 1, confidence: 87 },
      ],
      eventCount: 1,
    },
  },
];
